/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jcrtguwyireejxitrjiu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjcnRndXd5aXJlZWp4aXRyaml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5NzEwMTUsImV4cCI6MjA5NjU0NzAxNX0.3nBTdgGqfOsvMYCF2yV-ak-aaf9xie2LEQd0eVZuwUo"